services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: userpwd
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITIDB_ROOT_USERNAME=root
      - MONGO_INITIDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  
volumes:
  mongodata:
    driver: local